# Generated by Django 6.1.1 on 2026-09-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('destination_preference', models.CharField(help_text='Preferred destination or region', max_length=150)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, default=7, null=True)),
                ('travelers_count', models.PositiveIntegerField(default=2)),
                ('budget_range', models.CharField(blank=True, help_text='e.g., $2000 - $5000', max_length=100)),
                ('preferences', models.TextField(blank=True, help_text='Luxury, Adventure, Family-friendly, Honeymoon, etc.')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('IN_DISCUSSION', 'In Discussion'), ('QUOTE_SENT', 'Quote Sent'), ('CONVERTED', 'Converted to Booking'), ('CLOSED', 'Closed')], default='NEW', max_length=30)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Enquiry',
                'verbose_name_plural': 'Custom Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryCommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone Call'), ('WHATSAPP', 'WhatsApp'), ('INTERNAL', 'Internal Note')], default='EMAIL', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='enquiries.customenquiry')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
