# Generated by Django 6.1.1 on 2026-09-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('overview', models.TextField(help_text='Detailed overview of what makes this holiday special')),
                ('duration_days', models.PositiveIntegerField(default=5)),
                ('duration_nights', models.PositiveIntegerField(default=4)),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Starting price per traveler', max_digits=10)),
                ('pricing_basis', models.CharField(choices=[('PER_PERSON', 'Per Person'), ('PER_COUPLE', 'Per Couple'), ('PER_GROUP', 'Per Group')], default='PER_PERSON', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packages/covers/')),
                ('inclusions', models.TextField(help_text='List of items included (one per line or JSON format)')),
                ('exclusions', models.TextField(help_text='List of items excluded (one per line or JSON format)')),
                ('travel_requirements', models.TextField(blank=True, help_text='Passport, visa, health or travel insurance details')),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Travel Package',
                'verbose_name_plural': 'Travel Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(help_text='e.g., Arrival in Bali & Sunset Dinner', max_length=200)),
                ('description', models.TextField()),
                ('activities', models.TextField(blank=True, help_text='Key activities scheduled for the day')),
                ('meals', models.CharField(blank=True, help_text='e.g., Breakfast, Dinner', max_length=100)),
                ('accommodation', models.CharField(blank=True, help_text='Hotel / Resort stay info', max_length=150)),
                ('transport', models.CharField(blank=True, help_text='Private Coach, Speedboat, Flight', max_length=150)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='packages.travelpackage')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
