# Generated by Django 6.1.1 on 2026-09-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='JPT Holidays', max_length=100)),
                ('tagline', models.CharField(default='Your Trusted Travel & Bespoke Holiday Partner', max_length=255)),
                ('contact_email', models.EmailField(default='info@jptholidays.placeholder', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) JPT-HOLIDAY [Placeholder]', max_length=50)),
                ('whatsapp_number', models.CharField(default='+1 (555) 019-2834 [Placeholder]', max_length=50)),
                ('office_address', models.TextField(default='123 Premium Travel Way, Tourism District [Placeholder]')),
                ('business_hours', models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM EST', max_length=100)),
                ('currency_code', models.CharField(default='USD', max_length=10)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/jptholidays.placeholder')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/jptholidays.placeholder')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/jptholidays.placeholder')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/jptholidays.placeholder')),
                ('about_text', models.TextField(default='JPT Holidays provides tailored travel experiences, luxury destination packages, and custom itineraries for travelers around the globe.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
