# Generated by Django 6.1.1 on 2026-09-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(help_text='Transaction ref or Bank receipt number', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Direct Wire / Transfer'), ('CASH', 'Cash Payment'), ('CREDIT_CARD', 'Credit / Debit Card'), ('ONLINE_GATEWAY', 'Online Gateway (Stripe/PayPal)')], default='BANK_TRANSFER', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified / Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('receipt_document', models.FileField(blank=True, help_text='Proof of payment upload', null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='bookings.booking')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
